### ISSUE TITLE
Krushkal Algorithm

### ISSUE THREAD

**Issue by Vrushti24** [DankIndianCoders/Algorithms#10]
Write a Program to implement Krushkal Algorithm for minimum Spanning Tree in C Programming language

**Comment by Vrushti24** [comment]
@DankIndianCoders please assign me

**Comment by thesmartdeveloperr** [comment]
pls contribute. would love to see your PR. also follow the contributing guidelines..

**Comment by Vrushti24** [comment]
ADDED PR #11
